nfvbenchvm: abort build on error
Make sure a VM image build fails if any step fails.  Else we can end up
with a bad image not containing all that we want, and we discover this
later at run time.

For instance, without the current patch, we can get a generator VM image
without nfvbench installed because "pip install" failed, but this is not
detected by the build process because the last step in
post-install.d/52-nfvbench-script is an "echo" command that returns a
success code.

We fix this by making all the Bash scripts fail if any command whose
return code is not tested fails (set -euo pipefail).

Change-Id: Ic5ec9eb85a8d6e7e4d1dcbac8ebcac5931e4808e
Signed-off-by: Gwenael Lambrouin <gwenael.lambrouin@orange.com>

diff --git a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/01-update-kernel b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/01-update-kernel
--- a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/01-update-kernel
+++ b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/01-update-kernel
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Stop on error
+set -euo pipefail
+
 if [ $DIB_USE_ELREPO_KERNEL != "True" ]; then
     exit 0
 fi
diff --git a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/03-copy-rc-local b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/03-copy-rc-local
--- a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/03-copy-rc-local
+++ b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/03-copy-rc-local
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Stop on error
+set -euo pipefail
+
 # set accurate rc.local file corresponding to current image built
 if [ $DIB_DEV_IMAGE = "loopvm" ]; then
     mv /etc/rc.d/rc.local.loopvm /etc/rc.d/rc.local
diff --git a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/52-nfvbench-script b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/52-nfvbench-script
--- a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/52-nfvbench-script
+++ b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/52-nfvbench-script
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Make sure the disk image build fails if nfvbench installation fails
+set -euo pipefail
+
 if [ $DIB_DEV_IMAGE != "generator" ]; then
     exit 0
 fi
diff --git a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/53-sshd-script b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/53-sshd-script
--- a/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/53-sshd-script
+++ b/nfvbenchvm/dib/elements/nfvbenchvm/post-install.d/53-sshd-script
@@ -1,4 +1,7 @@
 #!/bin/bash
 
+# Stop on error
+set -euo pipefail
+
 # Set UseDNS no value in sshd_config to reduce time to connect
 echo "UseDNS no" >> /etc/ssh/sshd_config
